import type { IconDefinition } from '@fortawesome/fontawesome-svg-core';
import {
  faArrowLeft,
  faArrowRight,
  faArrowUp,
  faArrowDown,
  faArrowTrendDown,
  faSort,
  faAward,
  faArrowsRotate,
  faBell,
  faBoxOpen,
  faBoxesStacked,
  faCalendarCheck,
  faCalendarDays,
  faCartShopping,
  faCheck,
  faCircleCheck,
  faCircleInfo,
  faCircleQuestion,
  faClockRotateLeft,
  faCloudArrowUp,
  faCloudBolt,
  faCloud,
  faComment,
  faCopy,
  faCreditCard,
  faDatabase,
  faDownload,
  faEnvelope,
  faEye,
  faFileLines,
  faFileShield,
  faFloppyDisk,
  faGear,
  faGavel,
  faGaugeHigh,
  faGlobe,
  faHandHoldingDollar,
  faHandshake,
  faHeadset,
  faHouse,
  faIdBadge,
  faImage,
  faKey,
  faLayerGroup,
  faLocationDot,
  faMagnifyingGlass,
  faMap,
  faMapLocationDot,
  faMapPin,
  faMessage,
  faMicrochip,
  faMotorcycle,
  faNetworkWired,
  faPaperPlane,
  faPause,
  faPenToSquare,
  faPhone,
  faPhoneVolume,
  faPlay,
  faPlus,
  faReceipt,
  faRightFromBracket,
  faRotate,
  faRoute,
  faServer,
  faShareNodes,
  faShieldHalved,
  faShieldHeart,
  faShop,
  faSliders,
  faStar,
  faStore,
  faTableCellsLarge,
  faTag,
  faTruckFast,
  faUmbrella,
  faUpRightFromSquare,
  faUser,
  faUserGear,
  faUserPlus,
  faUtensils,
  faWallet,
  faWandMagicSparkles,
  faXmark,
  faCircleExclamation,
  faCircleXmark,
  faCircleDot,
  faChevronLeft,
  faChevronRight,
  faBasketShopping,
  faCarSide,
  faFileArrowDown,
  faFingerprint,
  faShield,
  faCircleHalfStroke,
  faList,
  faLocationCrosshairs,
  faListCheck,
  faMagnifyingGlassMinus,
  faMagnifyingGlassPlus,
  faPaperclip,
  faLink,
  faCommentDots,
  faFaceSmile,
  faHourglassHalf,
  faTriangleExclamation,
  faAppleWhole,
  faBan,
  faBellSlash,
  faBowlFood,
  faBreadSlice,
  faBurger,
  faCashRegister,
  faGlassWater,
  faHammer,
  faIceCream,
  faKitchenSet,
  faLeaf,
  faMartiniGlass,
  faMugHot,
  faMugSaucer,
  faSackDollar,
  faSeedling,
  faUsers,
  faWheatAwn,
  faBriefcase,
  faCircleUser,
  faEyeSlash,
  faChevronDown,
  faAngleRight,
  faEgg
} from '@fortawesome/free-solid-svg-icons';

/**
 * Tables d'icônes Font Awesome du projet.
 *
 * La maquette exportée de Stitch écrit ses icônes en ligatures Material Symbols (`shopping_cart`,
 * `local_shipping`…). Plutôt que d'embarquer la police de 3,9 Mo, chaque nom est mis en
 * correspondance avec un tracé Font Awesome, rendu soit par le composant `FaIcon`, soit en chaîne de
 * caractères par `markupIcone` (les scripts du design, qui écrivent du HTML, en ont besoin).
 *
 * Séparé du composant pour que le module reste « un seul composant exporté » (Fast Refresh) et pour
 * que la table ait UNE source de vérité : un nom absent bascule sur `faCircleQuestion`, visible,
 * jamais sur une icône manquante. Contrôlé par `tests/fa-icones-couvertes.test.ts`.
 */
/**
 * Table de correspondance : ligature Material Symbols (telle que la maquette l'écrit) -> icône
 * Font Awesome. Exportée pour que les scripts du design, qui écrivent du HTML en chaînes, puissent
 * produire le même tracé que le composant (voir `markupIcone` dans `utils/designRuntime`).
 */
export const ICONES_MATERIAL: Record<string, IconDefinition> = {
  arrow_forward_ios: faAngleRight,
  done: faCheck,
  egg: faEgg,
  play_arrow: faPlay,
  account_balance_wallet: faWallet,
  add: faPlus,
  add_circle: faCircleDot,
  add_location_alt: faMapPin,
  add_moderator: faShieldHeart,
  admin_panel_settings: faUserGear,
  api: faLink,
  arrow_back: faArrowLeft,
  arrow_forward: faArrowRight,
  arrow_upward: faArrowUp,
  attach_file: faPaperclip,
  auto_delete: faRotate,
  badge: faIdBadge,
  block: faCircleXmark,
  bolt: faCircleDot,
  build: faWandMagicSparkles,
  cached: faArrowsRotate,
  calendar_month: faCalendarDays,
  calendar_today: faCalendarDays,
  call: faPhone,
  cancel: faCircleXmark,
  settings: faGear,
  category: faTag,
  chat: faComment,
  chat_bubble: faMessage,
  chat_bubble_outline: faCommentDots,
  check: faCheck,
  check_circle: faCircleCheck,
  chevron_left: faChevronLeft,
  chevron_right: faChevronRight,
  cleaning_services: faWandMagicSparkles,
  clear_all: faList,
  close: faXmark,
  cloud: faCloud,
  cloud_off: faCloud,
  cloud_sync: faCloudBolt,
  cloud_upload: faCloudArrowUp,
  content_copy: faCopy,
  attach_money: faWallet,
  credit_card: faCreditCard,
  dashboard: faTableCellsLarge,
  data_object: faBoxesStacked,
  database: faDatabase,
  delete: faXmark,
  devices_other: faServer,
  dispatch: faTruckFast,
  distance: faRoute,
  dns: faNetworkWired,
  done_all: faListCheck,
  download: faDownload,
  edit: faPenToSquare,
  edit_location: faMapPin,
  edit_square: faPenToSquare,
  email: faEnvelope,
  encrypted: faShieldHalved,
  error: faCircleExclamation,
  restaurant: faUtensils,
  event_available: faCalendarCheck,
  event_busy: faCalendarDays,
  expand_more: faChevronDown,
  face_nod: faCircleCheck,
  fiber_manual_record: faCircleDot,
  file_download: faFileArrowDown,
  fingerprint: faFingerprint,
  flag_2: faTag,
  format_list_bulleted: faList,
  gavel: faGavel,
  grid_view: faTableCellsLarge,
  handshake: faHandshake,
  hard_drive: faServer,
  headset_mic: faHeadset,
  help: faCircleQuestion,
  history: faClockRotateLeft,
  history_edu: faFileLines,
  home: faHouse,
  hourglass_top: faHourglassHalf,
  hub: faNetworkWired,
  image: faImage,
  imagesmode: faImage,
  info: faCircleInfo,
  inventory: faBoxesStacked,
  inventory_2: faBoxOpen,
  key: faKey,
  lan: faNetworkWired,
  language: faGlobe,
  layers: faLayerGroup,
  lightbulb: faWandMagicSparkles,
  livreur: faTruckFast,
  local_shipping: faTruckFast,
  location_on: faLocationDot,
  lock: faShieldHalved,
  lock_open: faShield,
  lock_reset: faArrowsRotate,
  login: faArrowRight,
  logout: faRightFromBracket,
  mail: faEnvelope,
  manage_accounts: faUserGear,
  map: faMap,
  my_location: faLocationCrosshairs,
  mark_email_read: faEnvelope,
  memory: faMicrochip,
  mode_comment: faComment,
  mood: faFaceSmile,
  motorcycle: faMotorcycle,
  near_me: faLocationDot,
  network_check: faNetworkWired,
  nightlight: faCircleHalfStroke,
  notifications: faBell,
  notifications_active: faBell,
  nutrition: faBasketShopping,
  open_in_new: faUpRightFromSquare,
  package_2: faBoxOpen,
  password: faKey,
  pause: faPause,
  payments: faHandHoldingDollar,
  pending_actions: faListCheck,
  percent: faTag,
  person: faUser,
  person_add: faUserPlus,
  phone_iphone: faPhoneVolume,
  pin_drop: faMapPin,
  policy: faFileShield,
  psychiatry: faWandMagicSparkles,
  queue: faList,
  rainy: faUmbrella,
  receipt_long: faReceipt,
  report: faTriangleExclamation,
  route: faRoute,
  refresh: faArrowsRotate,
  remove: faXmark,
  reorder: faList,
  replay: faRotate,
  restart_alt: faRotate,
  save: faFloppyDisk,
  schedule: faClockRotateLeft,
  search: faMagnifyingGlass,
  search_off: faMagnifyingGlassMinus,
  security: faShieldHalved,
  security_update_good: faShieldHeart,
  send: faPaperPlane,
  share: faShareNodes,
  share_location: faMapLocationDot,
  shield: faShield,
  shield_lock: faShieldHalved,
  shopping_bag: faBasketShopping,
  shopping_basket: faBasketShopping,
  shopping_cart: faCartShopping,
  smart_toy: faWandMagicSparkles,
  sms: faMessage,
  speed: faGaugeHigh,
  star: faStar,
  ssid_chart: faNetworkWired,
  store: faShop,
  storefront: faStore,
  support_agent: faHeadset,
  arrow_downward: faArrowDown,
  trending_down: faArrowTrendDown,
  sort: faSort,
  sync: faArrowsRotate,
  sync_saved_locally: faCloud,
  task_alt: faCircleCheck,
  terminal: faServer,
  timelapse: faHourglassHalf,
  timer: faClockRotateLeft,
  tips_and_updates: faWandMagicSparkles,
  travel_explore: faGlobe,
  trending_up: faArrowUp,
  tune: faSliders,
  two_wheeler: faMotorcycle,
  verified: faCircleCheck,
  verified_user: faShieldHeart,
  view_list: faList,
  visibility: faEye,
  vpn_key: faKey,
  vpn_key_alert: faKey,
  warning: faTriangleExclamation,
  workspace_premium: faAward,
  webhook: faLink,
  zoom_in: faMagnifyingGlassPlus,
  zoom_out: faMagnifyingGlassMinus,
  car: faCarSide,
  flag: faTag,
  list: faList,
  list_check: faListCheck,
  play: faPlay,
  account_circle: faCircleUser,
  group: faUsers,
  visibility_off: faEyeSlash,
  work: faBriefcase,
  alarm_off: faBellSlash,
  bakery_dining: faBreadSlice,
  broken_image: faImage,
  coffee: faMugHot,
  daily_essentials: faBasketShopping,
  delivery_dining: faTruckFast,
  eco: faLeaf,
  emoji_food_beverage: faMugSaucer,
  festival: faStore,
  freshness: faAppleWhole,
  grain: faWheatAwn,
  hardware: faHammer,
  icecream: faIceCream,
  kitchen: faKitchenSet,
  liquor: faMartiniGlass,
  local_dining: faUtensils,
  local_drink: faGlassWater,
  local_florist: faSeedling,
  local_grocery_store: faBasketShopping,
  local_offer: faTag,
  lunch_dining: faBurger,
  market: faStore,
  no_meals: faBan,
  point_of_sale: faCashRegister,
  potted_plant: faSeedling,
  price_change: faSackDollar,
  production_quantity_limits: faBoxOpen,
  ramen_dining: faBowlFood,
  sell: faTag,
  set_meal: faUtensils,
  supervisor_account: faUsers,
  yard: faSeedling,
};

/** Balise `<svg>` Font Awesome en chaîne, pour le HTML produit par les scripts du design. */
export function markupIcone(nom: string, classes = ''): string {
  const definition = ICONES_MATERIAL[nom] ?? faCircleQuestion;
  const [largeur, hauteur, , , ...traces] = definition.icon;
  const chemins = traces.filter((t): t is string => typeof t === 'string').join('');
  const ratio = (largeur / hauteur).toFixed(3);
  const style = `width:${ratio}em;height:1em;vertical-align:-.125em`;
  return (
    `<svg viewBox="0 0 ${largeur} ${hauteur}" class="${classes}" style="${style}" ` +
    `fill="currentColor" aria-hidden="true" focusable="false">${chemins}</svg>`
  );
}
